### ISSUE TITLE
Dataset Upload

### ISSUE THREAD

**Issue by yeong-dev** [yeong5366/MS-UDA#2]
Since we have no specific storage or server for our dataset, I appreciate it if you could leave your mail address here. We can send it as soon as possible (6 pm ~ 12 am in KST).

**Comment by fengzhenHIT** [comment]
Dear yeong5366,
    I would like to use your dataset to test my project. If it is approved, please send it to me. Thank you very much. 
    My email is fengzhen@hit.edu.cn.

**Comment by yeong-dev** [comment]
I attached the dataset by email :) Have a nice day!

**Comment by ganlumomo** [comment]
Dear author,

I would like to use your KP dataset in my project and will cite your paper in my future publication.
My email is ganlu@caltech.edu. Thank you and I look forward to hearing from you.

**Comment by yeong-dev** [comment]
I sent it by email ;) I expect your project or publication! Have a great day!

**Comment by leofansq** [comment]
Dear author,
Thanks for your efforts ! I would like to use your KP dataset in my project for testing. My email is fansiqi2019@ia.ac.cn. Thank you and I look forward to hearing from you.

**Comment by yeong5366** [comment]
I sent the dataset by email. Have a great day :)
I can't wait for your future work. I hope I could see it soon.

**Comment by yeong-dev** [comment]
I sent the dataset by email. Have a great day :)
I can't wait for your future work. I hope I could see it soon.

**Comment by yeong5366** [comment]
> I sent the dataset by email. Have a great day :)
> I can't wait for your future work. I hope I could see it soon.

**Comment by leofansq** [comment]
> I sent the dataset by email. Have a great day :) I can't wait for your future work. I hope I could see it soon.

Thanks a lot for sending the dataset ! The labels of the KP dataset can be easily found in /KPdataset/labels. However, it is hard to recognize the RGB-T image pairs mentioned in the paper (3786 daytime and 3542 nighttime) according to the directory name. Could you please help me with that ? or would you mind describing the file structure in detail ? Thanks !

**Comment by ganlumomo** [comment]
@leofansq  @yeong5366  Hi, could you please let me know how to open and extract the .egg files in ubuntu? Thank you a lot!

**Comment by leofansq** [comment]
> @leofansq @yeong5366 Hi, could you please let me know how to open and extract the .egg files in ubuntu? Thank you a lot!

I open and extract the files in Windows via Bandizip for now.

**Comment by ganlumomo** [comment]
@leofansq Dear Siqi, I have tried both ubuntu and mac, no luck. Don't have access to a windows computer now, could you please share your extracted data with me? My email address is given above. Thank you so much!

**Comment by leofansq** [comment]
> @leofansq Dear Siqi, I have tried both ubuntu and mac, no luck. Don't have access to a windows computer now, could you please share your extracted data with me? My email address is given above. Thank you so much!

@ganlumomo Hi, the extracted data is too large to send, so I compressed the KPdataset in zip version and sent the zip file with the email. By the way, I didn't recognize the RGB-T image pairs mentioned in the paper, if you can, could you please help me with that? Thank you so much !

**Comment by ganlumomo** [comment]
@leofansq Thank you so much and I have got the dataset. From my understanding, the annotated KP dataset only includes RGB images and the corresponding pseudo labels, the paired thermal images should be in the original KAIST Multispectral Pedestrian: [https://github.com/SoonminHwang/rgbt-ped-detection](https://github.com/SoonminHwang/rgbt-ped-detection).

**Comment by ganlumomo** [comment]
@yeong5366 Thank you again for providing the dataset!

**Comment by leofansq** [comment]
> @leofansq Thank you so much and I have got the dataset. From my understanding, the annotated KP dataset only includes RGB images and the corresponding pseudo labels, the paired thermal images should be in the original KAIST Multispectral Pedestrian: https://github.com/SoonminHwang/rgbt-ped-detection.

@ganlumomo get it, thanks a lot !

**Comment by yeong-dev** [comment]
> > I sent the dataset by email. Have a great day :) I can't wait for your future work. I hope I could see it soon.
> 
> Thanks a lot for sending the dataset ! The labels of the KP dataset can be easily found in /KPdataset/labels. However, it is hard to recognize the RGB-T image pairs mentioned in the paper (3786 daytime and 3542 nighttime) according to the directory name. Could you please help me with that ? or would you mind describing the file structure in detail ? Thanks !

Sorry This is my fault I forgot sending the textfile for validation filename.  Please see https://github.com/yeong5366/MS-UDA/tree/main/filenames_KP
I posted the full filenames for the dataset.
And I noticed that I compressed files to .egg. Thanks for letting me know about this big mistake :0

**Comment by hhuxuchang** [comment]
My email is [xuchang@hhu.edu.cn](mailto:xuchang@hhu.edu.cn). Thank you again for providing the dataset!

**Comment by LAW1223** [comment]
Dear yeong5366,

I would like to use your dataset to test my project. If it is approved, please send it to me. Thank you very much.
My email is [yliu292@connect.hkust-gz.edu.cn]. I will cite this project in my research. Thank you again!!!

Yexin Liu

**Comment by LiuZhu-CV** [comment]
My email is liuzhu_ssdut@foxmail.com. Thank you again for providing the dataset!

**Comment by yeong5366** [comment]
Sure I'll send until this midnight(Korea time)

2023년 4월 5일 (수) 오전 11:53, LiuZhu-CV ***@***.***>님이 작성:

**Comment by yeong-dev** [comment]
Please visit https://drive.google.com/file/d/1W6A8IZD2mlP7Olo-Kaoa-kl60PIAN4oI/view?usp=sharing
